backend update

diff --git a/.github/workflows/soar_publish.yml b/.github/workflows/soar_publish.yml
--- a/.github/workflows/soar_publish.yml
+++ b/.github/workflows/soar_publish.yml
@@ -30,7 +30,6 @@ jobs:
         run: |
           pip install -r utils/requirements.txt
 
-      # Investigate git commits, extracts updated files per commit, loop through commits and import in Splunk SOAR target
       - name: Publish Git commits to Splunk SOAR Cloud
         env:
           SOAR_TESTING_DEST_API_URL: ${{ vars.SOAR_TESTING_DEST_API_URL }}
@@ -42,16 +41,8 @@ jobs:
         run: |
           echo "Inspecting git branch ${{ github.ref }}"
           echo "Inspecting git commit ${{ github.sha }}"
-          echo "running command git log --pretty=%P -n 1 ${{ github.sha }}"
-          git log --pretty=%P -n 1 ${{ github.sha }}
-          echo ""
-          commit_details=$(git log --pretty=%P -n 1 ${{ github.sha }})
-          echo "list of commit identifiers: $commit_details"
-          DEST_API_URL=""
-          DEST_API_TOKEN=""
-          DEST_SCM_NAME=""
 
-          # Check if we are on the 'testing' branch
+          # Branch environment setup
           if [[ "${{ github.ref }}" == "refs/heads/testing" ]]; then
               echo "Environment target is Testing"
               DEST_API_URL=$SOAR_TESTING_DEST_API_URL
@@ -63,62 +54,40 @@ jobs:
               DEST_API_TOKEN=$SOAR_PROD_DEST_API_TOKEN
               DEST_SCM_NAME=$SOAR_PROD_DEST_SCM_NAME
           else
-              echo "Invalid branch. This workflow is only for 'testing' or 'main' branches, refusing to excute this against any other branch."
+              echo "Invalid branch. Exiting."
               exit 1
           fi
 
-          for parent in $commit_details; do
-              echo "Handling git commit id: $parent"
-              echo "running command git show"
-              git show --name-only --pretty="" $parent || true
+          commit_parents=$(git log --pretty=%P -n 1 ${{ github.sha }})
+          if [[ $(echo $commit_parents | wc -w) -gt 1 ]]; then
+              modified_files=$(git diff --name-only ${commit_parents[0]} ${commit_parents[1]})
+          else
+              modified_files=$(git show --name-only --pretty="" ${{ github.sha }})
+          fi
 
-              # Fetch modified files in the commit and store in an array
-              mapfile -t files_array < <(git show --name-only --pretty="" $parent | grep -E '\.json$|\.py$')
-              files=$(printf "\"%s\" " "${files_array[@]}")
-              echo "files: $files"
+          mapfile -t files_array < <(echo "$modified_files" | grep -E '\.json$|\.py$')
 
-              # Check that for every .json file there's a .py file and vice-versa
-              valid_files=()
-              for file in "${files_array[@]}"; do
-                  base_name="${file%.*}" # strip extension
-                  if [[ "$file" =~ \.json$ && " ${files_array[*]} " =~ " $base_name.py " ]] || 
-                    [[ "$file" =~ \.py$ && " ${files_array[*]} " =~ " $base_name.json " ]]; then
-                      valid_files+=("$file")
+          # Loop through pairs of files
+          for file in "${files_array[@]}"; do
+              base_name="${file%.*}" # strip extension
+
+              if [[ "$file" =~ \.json$ && " ${files_array[*]} " =~ " $base_name.py " ]]; then
+                  paired_files=("$file" "$base_name.py")
+                  OBJECT_TYPE=$(echo "$file" | grep -q 'custom_functions/' && echo "custom_function" || echo "playbook")
+
+                  tarball_path="/tmp/${base_name}.tgz"
+
+                  if [ "$OBJECT_TYPE" == "custom_function" ]; then
+                      adjusted_files=("${paired_files[@]/custom_functions\//}")
+                      cd custom_functions
+                      eval tar -czvf $tarball_path "${adjusted_files[@]}"
+                      cd ../
+                  else
+                      eval tar -czvf $tarball_path "${paired_files[@]}"
                   fi
-              done
 
-              if [ ${#valid_files[@]} -eq 0 ]; then
-                  echo "No matching pairs of .json and .py found for commit id: $parent. Skipping."
-                  continue
+                  # Call the SOAR publish Python backend
+                  echo "Running command: python3 utils/soar_publish.py --input_file \"$tarball_path\" --dest_target=\"$DEST_API_URL\" --dest_token=\"$DEST_API_TOKEN\" --dest_scm_name=\"$DEST_SCM_NAME\" --object_type \"$OBJECT_TYPE\""
+                  python3 utils/soar_publish.py --input_file "$tarball_path" --dest_target="$DEST_API_URL" --dest_token="$DEST_API_TOKEN" --dest_scm_name="$DEST_SCM_NAME" --object_type "$OBJECT_TYPE"
               fi
-
-              echo "list of updated files for commit id $parent:"
-              printf "%s\n" "${valid_files[@]}"
-
-              # Determine the object type
-              if echo "$files" | grep -q 'custom_functions/'; then
-              OBJECT_TYPE="custom_function"
-              else
-              OBJECT_TYPE="playbook"
-              fi
-
-              # Create tarball
-              tarball_path="/tmp/$parent.tgz"
-
-              if [ "$OBJECT_TYPE" == "custom_function" ]; then
-              # Adjust paths to be relative to current directory and tar the files
-              adjusted_files=("${files_array[@]/custom_functions\//}")
-              cd custom_functions
-              eval tar -czvf $tarball_path "${adjusted_files[@]}"
-              cd ../
-              else
-              eval tar -czvf $tarball_path $files
-              fi
-              
-              # Call the SOAR publish Python backend
-              echo "running command: python3 utils/soar_publish.py --input_file \"$tarball_path\" --dest_target=\"$DEST_API_URL\" --dest_token=\"$DEST_API_TOKEN\" --dest_scm_name=\"$DEST_SCM_NAME\" --object_type \"$OBJECT_TYPE\""
-              python3 utils/soar_publish.py --input_file "$tarball_path" --dest_target="$DEST_API_URL" --dest_token="$DEST_API_TOKEN" --dest_scm_name="$DEST_SCM_NAME" --object_type "$OBJECT_TYPE"
-
           done
-
-          exit 0
